#!/bin/sh

screen -dmS tarsession
screen -S tarsession -X stuff "sudo -i\ncd /mnt/running\ntar --use-compress-program=pbzip2 -cf ubuntu.tar.bz2 ubuntu/"

screen -S tarsession -X wait

screen -S tarsession -X quit

mv ubuntu.tar.bz2 /mnt/runner-will-upload/
