name: Windows RDP Github-runner ARM

on: workflow_dispatch

jobs:
  setup-rdp:
    uses: ./.github/workflows/reusable-windows-rdp.yml
    with:
      runs-on: windows-11-vs2026-arm
      runner-user: runneradmin

      cloudflared-asset: cloudflared-windows-amd64.exe
      timeout-minutes: 360
    secrets: inherit
