name: Windows RDP Github-runner x64

on: workflow_dispatch

jobs:
  setup-rdp:
    uses: ./.github/workflows/reusable-windows-rdp.yml
    with:
      runs-on: windows-latest
      runner-user: runneradmin
      timeout-minutes: 360
    secrets: inherit
